(function(){
  const SURL='https://zawatmovyrjcpgxkqcqq.supabase.co';
  const esc2=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const db2=window.db;
  if(!db2) return;
  async function getSession(){const r=await db2.auth.getSession();return r.data?.session||null}
  function toast(msg,ok=true){const p=document.getElementById('opPanel');if(!p)return;const n=document.createElement('div');n.className=ok?'ok':'error';n.textContent=msg;p.prepend(n);setTimeout(()=>n.remove(),3000)}
  async function noticeManagementV3(p){
    const r=await db2.from('member_directory').select('id,wing,flat_unit_number,full_name,registered_email').eq('active',true).order('wing').order('flat_unit_number');
    if(r.error)throw r.error;const members=r.data||[];
    p.innerHTML='<h2>📢 Notice Management</h2><div class="formGrid">'+
      '<label>Notice Title / सूचना शीर्षक<input id="ncTitle"></label><label>Category / प्रकार<input id="ncCategory" value="General"></label>'+
      '<label>Visibility / कोणाला दिसेल?<select id="ncScope" onchange="window.__toggleNoticeTarget()"><option value="public">🌐 Public</option><option value="all">👥 All Members</option><option value="specific">🎯 Specific Members</option></select></label>'+
      '<label class="full">Notice Body / सूचना मजकूर<textarea id="ncBody" rows="6"></textarea></label>'+
      '<label class="full">📎 Notice PDF / सूचना PDF<input id="ncPdf" type="file" accept="application/pdf,.pdf"></label>'+
      '<div id="ncTarget" class="full hidden"><b>Specific Members निवडा</b><input id="ncSearch" class="search" placeholder="नाव / Flat शोधा..." oninput="window.__filterNoticeMembers()"><div id="ncMembers" class="scroll" style="border:1px solid #e3d8bd;border-radius:10px;padding:8px"></div><div class="row"><button class="light" type="button" onclick="window.__selectNoticeMembers(true)">Select All</button><button class="light" type="button" onclick="window.__selectNoticeMembers(false)">Clear</button><span id="ncCount" class="muted">0 selected</span></div></div>'+
      '</div><div class="row" style="margin-top:12px"><button class="dark" onclick="window.__publishNoticeV3()">🚀 Publish Notice</button><span id="ncMsg"></span></div><h3>Existing Notices</h3><div id="ncList"></div>';
    window.__noticeMembers=members;window.__renderNoticeMembers=()=>{const q=(document.getElementById('ncSearch')?.value||'').toLowerCase();const box=document.getElementById('ncMembers');const rows=members.filter(x=>(x.full_name+' '+x.wing+'-'+x.flat_unit_number).toLowerCase().includes(q));box.innerHTML=rows.map(x=>'<label style="display:flex;gap:8px;align-items:center;padding:8px;border-bottom:1px solid #eee"><input type="checkbox" value="'+esc2(x.id)+'" onchange="window.__noticeCount()"><span><b>'+esc2(x.full_name||'Resident')+'</b><br><span class="small muted">'+esc2(x.wing+'-'+x.flat_unit_number)+'</span></span></label>').join('')||'<div class="empty">No matching member.</div>';window.__noticeCount()};window.__noticeCount=()=>{const n=document.querySelectorAll('#ncMembers input:checked').length;const c=document.getElementById('ncCount');if(c)c.textContent=n+' selected'};window.__toggleNoticeTarget=()=>document.getElementById('ncTarget').classList.toggle('hidden',document.getElementById('ncScope').value!=='specific');window.__filterNoticeMembers=window.__renderNoticeMembers;window.__selectNoticeMembers=v=>{document.querySelectorAll('#ncMembers input').forEach(x=>x.checked=v);window.__noticeCount()};window.__renderNoticeMembers();
    const n=await db2.from('notices').select('id,title,category,published,visibility_scope,pdf_file_name,created_at,published_at').order('created_at',{ascending:false});if(n.error)throw n.error;document.getElementById('ncList').innerHTML=n.data?.length?'<div class="tableWrap"><table><thead><tr><th>Title</th><th>Visibility</th><th>PDF</th><th>Status</th><th>Date</th></tr></thead><tbody>'+n.data.map(x=>'<tr><td>'+esc2(x.title)+'</td><td>'+esc2(x.visibility_scope)+'</td><td>'+esc2(x.pdf_file_name||'—')+'</td><td>'+esc2(x.published?'Published':'Draft')+'</td><td>'+esc2(x.created_at?new Date(x.created_at).toLocaleDateString():'')+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">No notices.</div>';
  }
  window.__publishNoticeV3=async function(){try{const scope=document.getElementById('ncScope').value,title=document.getElementById('ncTitle').value.trim(),body=document.getElementById('ncBody').value.trim(),pdf=document.getElementById('ncPdf').files[0];if(!title||!body)throw Error('Title and notice body are required.');const session=await getSession();if(!session)throw Error('Session expired. Please sign in again.');const payload={title,body,category:document.getElementById('ncCategory').value.trim()||'General',published:true,visibility_scope:scope,created_by:currentProfile.id,updated_by:currentProfile.id,published_at:new Date().toISOString()};const ins=await db2.from('notices').insert(payload).select('id').single();if(ins.error)throw ins.error;let path=null;if(scope==='specific'){const ids=[...document.querySelectorAll('#ncMembers input:checked')].map(x=>x.value);if(!ids.length)throw Error('Select at least one member.');const tr=await db2.from('notice_unit_targets').insert(ids.map(directory_id=>({notice_id:ins.data.id,target_scope:'specific',directory_id})));if(tr.error)throw tr.error}if(pdf){if(pdf.type!=='application/pdf')throw Error('Only PDF files are allowed.');path='notices/'+ins.data.id+'/'+Date.now()+'-'+pdf.name.replace(/[^a-zA-Z0-9._-]/g,'_');const up=await db2.storage.from('society-notice-pdfs').upload(path,pdf,{contentType:'application/pdf',upsert:false});if(up.error)throw up.error;const u=await db2.from('notices').update({pdf_storage_path:path,pdf_file_name:pdf.name,pdf_mime_type:'application/pdf'}).eq('id',ins.data.id);if(u.error)throw u.error}toast('Notice published successfully.');await noticeManagementV3(document.getElementById('opPanel'))}catch(e){toast(e.message||String(e),false)}};
  async function memberNoticesV3(p){const dir=await db2.from('member_directory').select('id').eq('active',true).eq('registered_email',currentProfile.email).maybeSingle();const q=await db2.from('notices').select('id,title,body,category,published_at,visibility_scope,pdf_file_name').eq('published',true).order('published_at',{ascending:false});if(q.error)throw q.error;let rows=q.data||[];if(dir.data){const t=await db2.from('notice_unit_targets').select('notice_id').eq('directory_id',dir.data.id);const ids=new Set((t.data||[]).map(x=>x.notice_id));rows=rows.filter(x=>x.visibility_scope!=='specific'||ids.has(x.id))}else rows=rows.filter(x=>x.visibility_scope!=='specific');p.innerHTML='<h2>'+((window.T?.[window.lang]?.notices)||'Notices')+'</h2>'+(rows.map(x=>'<div class="detailCard" style="margin-top:10px"><b>'+esc2(x.title)+'</b><div class="muted small">'+esc2(x.category||'General')+' · '+esc2(x.published_at?new Date(x.published_at).toLocaleDateString():'')+'</div><p>'+esc2(x.body)+'</p>'+(x.pdf_file_name?'<button class="light" onclick="window.__openNoticePdf(\''+esc2(x.id)+'\')">📎 Open PDF</button>':'')+'</div>').join('')||'<div class="empty">No notices.</div>')}
  window.__openNoticePdf=async id=>{try{const session=await getSession();const h=session?{Authorization:'Bearer '+session.access_token}:{};const r=await fetch(SURL+'/functions/v1/content-signed-url',{method:'POST',headers:{'content-type':'application/json',...h},body:JSON.stringify({type:'notice-pdf',id})});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to open PDF');window.open(j.url,'_blank','noopener')}catch(e){alert(e.message)}};
  async function galleryManagement(p){const a=await db2.from('gallery_albums').select('id,title,description,event_date,visibility_scope,published,created_at').order('event_date',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false});if(a.error)throw a.error;p.innerHTML='<h2>📸 Photo Gallery Management</h2><p class="muted">Create albums, choose visibility, upload multiple photos and publish/unpublish.</p><div class="formGrid"><label>Album / Event Name<input id="gaTitle"></label><label>Event Date<input id="gaDate" type="date"></label><label class="full">Description<textarea id="gaDesc" rows="3"></textarea></label><label>Visibility<select id="gaScope"><option value="public">🌐 Public</option><option value="members">👥 Members Only</option><option value="admin">🔐 Admin Only</option></select></label><label>Photos<input id="gaFiles" type="file" accept="image/*" multiple></label></div><div class="row" style="margin-top:12px"><button class="dark" onclick="window.__createGallery()">Create Album & Upload</button><span id="gaMsg"></span></div><h3>Albums</h3><div id="gaList"></div>';
    document.getElementById('gaList').innerHTML=a.data?.length?'<div class="tableWrap"><table><thead><tr><th>Album</th><th>Event Date</th><th>Visibility</th><th>Status</th><th>Photos</th><th>Action</th></tr></thead><tbody>'+a.data.map(x=>'<tr><td><b>'+esc2(x.title)+'</b><br><span class="small muted">'+esc2(x.description||'')+'</span></td><td>'+esc2(x.event_date||'—')+'</td><td>'+esc2(x.visibility_scope)+'</td><td>'+esc2(x.published?'Published':'Unpublished')+'</td><td><button class="light" onclick="window.__viewAlbum(\''+esc2(x.id)+'\')">View</button></td><td><button class="light" onclick="window.__toggleAlbum(\''+esc2(x.id)+'\','+(!x.published)+')">'+(x.published?'Unpublish':'Publish')+'</button> <button class="light" onclick="window.__deleteAlbum(\''+esc2(x.id)+'\')">Delete</button></td></tr>').join('')+'</tbody></table></div>':'<div class="empty">No albums yet.</div>'}
  }
  window.__createGallery=async()=>{try{const title=document.getElementById('gaTitle').value.trim(),scope=document.getElementById('gaScope').value,files=[...document.getElementById('gaFiles').files];if(!title)throw Error('Album name is required.');if(!files.length)throw Error('Select at least one photo.');const ins=await db2.from('gallery_albums').insert({title,description:document.getElementById('gaDesc').value.trim(),event_date:document.getElementById('gaDate').value||null,visibility_scope:scope,published:false,created_by:currentProfile.id}).select('id').single();if(ins.error)throw ins.error;const bucket=scope==='public'?'society-gallery-public':'society-gallery-private';for(let i=0;i<files.length;i++){const f=files[i];if(!f.type.startsWith('image/'))continue;const path='albums/'+ins.data.id+'/'+Date.now()+'-'+i+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const up=await db2.storage.from(bucket).upload(path,f,{contentType:f.type,upsert:false});if(up.error)throw up.error;const ph=await db2.from('gallery_photos').insert({album_id:ins.data.id,storage_path:path,file_name:f.name,sort_order:i,created_by:currentProfile.id});if(ph.error)throw ph.error}toast('Album created with '+files.length+' photo(s).');await galleryManagement(document.getElementById('opPanel'))}catch(e){toast(e.message||String(e),false)}};
  window.__toggleAlbum=async(id,published)=>{const r=await db2.from('gallery_albums').update({published,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)toast(r.error.message,false);else galleryManagement(document.getElementById('opPanel'))};
  window.__deleteAlbum=async id=>{if(!confirm('Delete this album and its photo records?'))return;const r=await db2.from('gallery_albums').delete().eq('id',id);if(r.error)toast(r.error.message,false);else galleryManagement(document.getElementById('opPanel'))};
  window.__viewAlbum=async id=>{const r=await db2.from('gallery_photos').select('id,file_name,storage_path,sort_order').eq('album_id',id).order('sort_order');if(r.error)throw r.error;const p=document.getElementById('opPanel');p.innerHTML='<button class="light" onclick="window.__backGallery()">← Back to Albums</button><h2>Album Photos</h2><div class="detailGrid">'+(r.data||[]).map(x=>'<div class="detailCard"><div style="aspect-ratio:4/3;background:#eee;border-radius:10px;overflow:hidden"><img id="gp'+esc2(x.id)+'" style="width:100%;height:100%;object-fit:cover" alt=""></div><div class="small" style="margin-top:8px">'+esc2(x.file_name)+'</div></div>').join('')+'</div>';for(const x of r.data||[]){const s=await fetch(SURL+'/functions/v1/content-signed-url',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'gallery',id:x.id})});const j=await s.json();if(s.ok&&j.url){const im=document.getElementById('gp'+x.id);if(im)im.src=j.url}}};window.__backGallery=()=>galleryManagement(document.getElementById('opPanel'));
  const oldLoadOp=window.loadOp;window.loadOp=async function(op){if(op==='gallery')return galleryManagement(document.getElementById('opPanel'));return oldLoadOp(op)};
  const oldMemberNotices=window.memberNotices;window.memberNotices=memberNoticesV3;
  function addGalleryButton(){const nav=document.querySelector('.adminMenu');if(!nav||nav.querySelector('[data-op="gallery"]'))return;const b=document.createElement('button');b.dataset.op='gallery';b.innerHTML='📸 <span>Photo Gallery</span>';b.onclick=()=>window.loadOp('gallery');nav.appendChild(b)}
  const oldAdminLoad=window.adminLoad;window.adminLoad=async function(){await oldAdminLoad();addGalleryButton()};
  if(document.readyState!=='loading')setTimeout(addGalleryButton,500);else document.addEventListener('DOMContentLoaded',()=>setTimeout(addGalleryButton,500));
})();